# This is a basic workflow to help you get started with Actions

name: Jig Deploy
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: https://registry.npmjs.org/
    - run: npm install yarn
    - run: yarn --cwd jig
      env:
        CI: true
    - run: yarn --cwd jig clean
      env:
        CI: true
    - run: yarn --cwd jig build
      env:
        CI: true
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      working-directory: jig/dist
    - run: yarn --cwd jigcss
      env:
        CI: true
    - run: yarn --cwd jigcss clean
      env:
        CI: true
    - run: yarn --cwd jigcss build
      env:
        CI: true
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      working-directory: jigcss/dist
